### ISSUE TITLE
curious to understand jdk vs jre..

### ISSUE THREAD

**Issue by eitansuez** [bosh-packages/java-release#5]
it appears that the package provided here provides only a jre and not a full jdk.  is that right?
when i ssh to a machine with this package installed, i see java but not javac (for example) in /var/vcap/packages/openjdk-8/ (under jre/bin).

i know some releases that depend on java require a full jdk, not just the jre.
where would i go to get that?

thanks, / eitan

**Comment by JCL38-ORANGE** [comment]
Hello,

I agree.
The java package vendoring needs to provide with a full jdk in order to compile a broker embedded in a bosh release for example. 
Thanks and regards in advance for your feedback.
Jean-Christophe.

**Comment by cppforlife** [comment]
hey @eitansuez @JCL38-ORANGE, reason why jre is only included is because that's what's typically necessary for running prebuilt java software (such as zookeeper, kafka, etc.). i havent included built jdk because i havent myself run into case where i needed it. i assume yall are compiling java apps within a compilation script and that's why you need jdk as well?

**Comment by eitansuez** [comment]
that's a good point:  what's a good use case?  i'm not sure.  the obvious one is a release that builds a java package from source.  when i push java or spring apps to cloudfoundry, the java buildpack bundles a jdk, not just a jre.  why?  we could ask ben hale i suppose.  in my experience i've encountered situations installing a java-based app where the installation instructions are specific about requiring a full copy of the jdk and not just the jre as the runtime;  i forget what the exact reason is.  i want to say gemfire is an example, but i'd have to check.
